export const products = [
  {
    id: 1,
    name: 'Engine Block',
    brand: 'Ford',
    model: 'F-150',
    type: 'Engine',
    price: 499.99,
    condition: 'new',
    stock: true,
    rating: 4.8,
    partNumber: 'ENG-F150-001',
    description:
      'High-quality engine block designed for Ford F-150 vehicles. Made from durable cast iron for long-lasting performance.',
    detailDescription:
      'The Engine Block is an essential component of any Ford F-150, forming the core structure of the vehicle’s powertrain. This high-quality replacement is crafted from premium-grade cast iron, offering superior strength and heat resistance. Designed to meet OEM specifications, it ensures a perfect fit and seamless integration into your F-150’s engine bay. Whether you’re restoring an older model or upgrading your current engine, this block provides a reliable foundation for performance builds and daily drivers alike. Its reinforced design improves durability under high-stress conditions, making it ideal for towing, off-roading, or high-performance applications. The engine block includes all necessary mounting points and oil passages to support a complete engine rebuild or swap. Choose this engine block for unmatched reliability and longevity in your Ford F-150.',

    primaryImage: '/images/parts/Engine Block.png',
    secondaryImages: [
      '/images/parts/Engine Block.png',
      '/images/parts/Engine Block.png',
    ],
    specifications: [
      { label: 'Material', value: 'Cast Iron' },
      { label: 'Dimensions', value: '24 x 18 x 12 inches' },
      { label: 'Weight', value: '75 lbs' },
      { label: 'Compatibility', value: 'Ford F-150 2010–2020' },
      { label: 'Warranty', value: '1 Year' },
    ],
    features: [
      'Durable cast iron construction',
      'Perfect fit for Ford F-150 engines',
      'Improved heat resistance and strength',
    ],
    tags: ['engine', 'ford', 'f150', 'replacement', 'performance'],
  },
  {
    id: 2,
    name: 'Transmission Gearbox',
    brand: 'Chevrolet',
    model: 'Silverado',
    type: 'Transmission',
    price: 699.99,
    condition: 'used',
    stock: true,
    rating: 4.5,
    partNumber: 'TRANS-SILV-002',
    description:
      'Used but well-maintained transmission gearbox for Chevrolet Silverado. Fully tested and ready to install.',
    primaryImage: '/images/parts/transmission-main.jpg',
    secondaryImages: [
      '/images/parts/transmission-angle.jpg',
      '/images/parts/transmission-packaging.jpg',
    ],
    specifications: [
      { label: 'Type', value: 'Automatic' },
      { label: 'Gear Count', value: '6 Speed' },
      { label: 'Compatibility', value: 'Chevy Silverado 2015–2018' },
      { label: 'Condition', value: 'Used - Good' },
      { label: 'Warranty', value: '3 Months' },
    ],
    features: [
      'Reconditioned with updated seals and gaskets',
      'Smooth shifting performance',
      'Includes torque converter',
    ],
    tags: ['transmission', 'chevrolet', 'silverado', 'used', 'automatic'],
  },
  {
    id: 3,
    name: 'Front Bumper',
    brand: 'Toyota',
    model: 'Camry',
    type: 'Bumpers',
    price: 199.99,
    condition: 'used',
    stock: true,
    rating: 4.7,
    partNumber: 'BUMPER-CAMRY-003',
    description:
      'Genuine Toyota front bumper assembly for Camry models. Minor scratches, fully functional.',
    primaryImage: '/images/parts/front-bumper-main.jpg',
    secondaryImages: [
      '/images/parts/front-bumper-angle.jpg',
      '/images/parts/front-bumper-packaging.jpg',
    ],
    specifications: [
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Compatibility', value: 'Toyota Camry 2012–2017' },
      { label: 'Finish', value: 'Paintable Black Primer' },
      { label: 'Condition', value: 'Used - Light Scratches' },
      { label: 'Warranty', value: 'No Warranty' },
    ],
    features: [
      'OEM quality direct replacement',
      'Easy bolt-on installation',
      'Includes mounting hardware',
    ],
    tags: ['bumper', 'toyota', 'camry', 'used', 'replacement'],
  },
  {
    id: 4,
    name: 'Rear Axle',
    brand: 'Dodge',
    model: 'Ram',
    type: 'Drive Shaft & Axles',
    price: 349.99,
    condition: 'new',
    stock: false,
    rating: 4.2,
    partNumber: 'AXLE-RAM-004',
    description:
      'New rear axle assembly for Dodge Ram trucks. OEM compatible with high-strength steel construction.',
    primaryImage: '/images/parts/rear-axle-main.jpg',
    secondaryImages: [
      '/images/parts/rear-axle-angle.jpg',
      '/images/parts/rear-axle-packaging.jpg',
    ],
    specifications: [
      { label: 'Type', value: 'Solid Axle' },
      { label: 'Material', value: 'Forged Steel' },
      { label: 'Compatibility', value: 'Dodge Ram 1500 2010–2018' },
      { label: 'Warranty', value: '6 Months' },
      { label: 'Stock Status', value: 'Currently Out of Stock' },
    ],
    features: [
      'Precision-engineered for OE fit',
      'Corrosion-resistant finish',
      'Heavy-duty design for towing',
    ],
    tags: ['axle', 'dodge', 'ram', 'steel', 'heavy-duty'],
  },
  {
    id: 5,
    name: 'Left Fender',
    brand: 'Honda',
    model: 'Civic',
    type: 'Fenders',
    price: 129.99,
    condition: 'used',
    stock: true,
    rating: 4.6,
    partNumber: 'FENDER-CIVIC-005',
    description:
      'Used left fender for Honda Civic. Minor paint imperfections, no dents or rust.',
    primaryImage: '/images/parts/left-fender-main.jpg',
    secondaryImages: [
      '/images/parts/left-fender-angle.jpg',
      '/images/parts/left-fender-packaging.jpg',
    ],
    specifications: [
      { label: 'Material', value: 'Steel' },
      { label: 'Color', value: 'Black (Paint Ready)' },
      { label: 'Compatibility', value: 'Honda Civic 2006–2011' },
      { label: 'Condition', value: 'Used - Some Paint Wear' },
      { label: 'Warranty', value: 'No Warranty' },
    ],
    features: [
      'Direct OEM replacement',
      'Pre-drilled mounting holes',
      'Ready to paint and install',
    ],
    tags: ['fender', 'honda', 'civic', 'used', 'body'],
  },
  {
    id: 6,
    name: 'Door Panel',
    brand: 'BMW',
    model: '3 Series',
    type: 'Doors',
    price: 249.99,
    condition: 'new',
    stock: true,
    rating: 4.9,
    partNumber: 'DOOR-BMW-006',
    description:
      'Brand new interior door panel for BMW 3 Series. Includes switches and armrest.',
    primaryImage: '/images/parts/door-panel-main.jpg',
    secondaryImages: [
      '/images/parts/door-panel-angle.jpg',
      '/images/parts/door-panel-packaging.jpg',
    ],
    specifications: [
      { label: 'Material', value: 'Plastic + Soft Touch Trim' },
      { label: 'Compatibility', value: 'BMW 3 Series E90/E92' },
      { label: 'Includes', value: 'Window Switch, Door Handle' },
      { label: 'Warranty', value: '1 Year' },
    ],
    features: [
      'Factory-style finish',
      'Plug-and-play wiring harness',
      'Scratch-resistant surface',
    ],
    tags: ['door', 'bmw', '3-series', 'interior', 'panel'],
  },
  {
    id: 7,
    name: 'V8 Turbocharged Engine',
    brand: 'Ford',
    model: 'Mustang',
    type: 'Engine',
    price: 899.99,
    condition: 'new',
    stock: true,
    rating: 4.7,
    partNumber: 'ENG-MUSTANG-V8-007',
    description:
      'Turbocharged V8 engine built for power and performance. Ideal for Mustang builds or replacements.',
    primaryImage: '/images/parts/v8-engine-main.jpg',
    secondaryImages: [
      '/images/parts/v8-engine-angle.jpg',
      '/images/parts/v8-engine-packaging.jpg',
    ],
    specifications: [
      { label: 'Type', value: 'V8 Turbocharged' },
      { label: 'Horsepower', value: '650 HP' },
      { label: 'Compatibility', value: 'Ford Mustang GT500' },
      { label: 'Fuel Type', value: 'Gasoline' },
      { label: 'Warranty', value: '1 Year' },
    ],
    features: [
      'Forced induction turbo system',
      'Balanced crankshaft for smooth operation',
      'Includes intake manifold',
    ],
    tags: ['engine', 'v8', 'ford', 'mustang', 'turbo'],
  },
  {
    id: 8,
    name: 'Automatic Transmission',
    brand: 'Mercedes',
    model: 'E-Class',
    type: 'Transmission',
    price: 999.99,
    condition: 'used',
    stock: true,
    rating: 4.6,
    partNumber: 'TRANS-ECLASS-008',
    description:
      'Fully tested automatic transmission for Mercedes-Benz E-Class. Comes with full warranty.',
    primaryImage: '/images/parts/Automatic Transmission.jpg',
    secondaryImages: [
      '/images/parts/Automatic Transmission.jpg',
      '/images/parts/Automatic Transmission.jpg',
    ],
    specifications: [
      { label: 'Type', value: 'Automatic' },
      { label: 'Model', value: '7G-Tronic' },
      { label: 'Compatibility', value: 'Mercedes E-Class W212' },
      { label: 'Mileage', value: 'Low Mileage - Rebuilt' },
      { label: 'Warranty', value: '6 Months' },
    ],
    features: [
      'Rebuilt with updated internals',
      'Perfect for DIY rebuilds or upgrades',
      'Includes service manual',
    ],
    tags: ['transmission', 'mercedes', 'e-class', 'automatic', 'rebuild'],
  },
];
